// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzkqOEx7sh6P3DOCpfhNuPkwNWgPblNqU',
    appId: '1:470437720436:web:aae76c58560e1598367c21',
    messagingSenderId: '470437720436',
    projectId: 'lab-12-b27bb',
    authDomain: 'lab-12-b27bb.firebaseapp.com',
    storageBucket: 'lab-12-b27bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADA0S0924k69yWTEfaJjuPkczTizQhuXM',
    appId: '1:470437720436:android:9a7e950a2534e055367c21',
    messagingSenderId: '470437720436',
    projectId: 'lab-12-b27bb',
    storageBucket: 'lab-12-b27bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzDhQfQullIKX3_mpQclpD_EPTDSEHtTo',
    appId: '1:470437720436:ios:3621ac830a8d996a367c21',
    messagingSenderId: '470437720436',
    projectId: 'lab-12-b27bb',
    storageBucket: 'lab-12-b27bb.appspot.com',
    iosBundleId: 'com.example.lab122',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzDhQfQullIKX3_mpQclpD_EPTDSEHtTo',
    appId: '1:470437720436:ios:f40f4af12d784f1d367c21',
    messagingSenderId: '470437720436',
    projectId: 'lab-12-b27bb',
    storageBucket: 'lab-12-b27bb.appspot.com',
    iosBundleId: 'com.example.lab122.RunnerTests',
  );
}
